# Generated by Django 5.1.6 on 2025-03-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
    ]
