# Generated by Django 5.1.6 on 2025-03-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0003_expensescategory_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('isbn', models.CharField(max_length=13)),
                ('author', models.ManyToManyField(to='reldemo.author')),
            ],
        ),
    ]
