# Generated by Django 5.1.6 on 2025-03-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0005_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
