# Generated by Django 5.1.6 on 2025-03-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0006_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(),
        ),
    ]
