# Generated by Django 5.1.6 on 2025-03-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0008_book_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='story',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
