# Generated by Django 5.1.6 on 2025-03-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0009_book_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='books_pdfs/'),
        ),
    ]
