# Generated by Django 5.1.6 on 2025-03-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0010_book_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
