# Generated by Django 5.1.6 on 2025-03-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0012_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
