# Generated by Django 5.1.6 on 2025-03-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0013_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
