# Generated by Django 5.1.6 on 2025-03-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0014_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='book_images/default.jpg', null=True, upload_to='book_images/'),
        ),
    ]
