# Generated by Django 5.1.6 on 2025-03-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0015_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='story',
            field=models.CharField(max_length=500),
        ),
    ]
