# Generated by Django 5.1.6 on 2025-03-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0016_alter_book_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='story',
            field=models.TextField(),
        ),
    ]
