# Generated by Django 5.1.6 on 2025-03-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0019_category_remove_borrowedbook_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='reldemo.author'),
        ),
    ]
