# Generated by Django 5.1.7 on 2025-03-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0021_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
