# Generated by Django 5.1.7 on 2025-03-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0024_author_birth_date_author_nationality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=66, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
