# Generated by Django 5.1.7 on 2025-03-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0026_alter_book_options_book_categories_book_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
