# Generated by Django 5.1.7 on 2025-03-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0028_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
    ]
