# Generated by Django 5.1.7 on 2025-03-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0029_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(default='default.pdf', upload_to='books_pdfs/'),
        ),
    ]
