# Generated by Django 5.1.7 on 2025-05-12 01:53

import django.core.validators
import reldemo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0031_bookstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), reldemo.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(default='default.pdf', upload_to='books_pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), reldemo.validators.validate_file_size]),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='reldemo_boo_title_53b680_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='reldemo_boo_isbn_04176f_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['created_at'], name='reldemo_boo_created_4aa894_idx'),
        ),
    ]
