# Generated by Django 5.0.2 on 2025-05-12 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0032_alter_book_options_alter_book_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_goal', models.PositiveIntegerField(default=12)),
                ('preferred_genres', models.TextField(blank=True, help_text='JSON data of preferred genres with weights')),
                ('recommendation_history', models.TextField(blank=True, help_text='JSON data of recommendation history')),
                ('favorite_authors', models.ManyToManyField(blank=True, related_name='favorited_by', to='reldemo.author')),
                ('favorite_categories', models.ManyToManyField(blank=True, related_name='favorited_by', to='reldemo.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
